//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoRentDatabaseEntitiesActual : DbContext
    {
        public AutoRentDatabaseEntitiesActual()
            : base("name=AutoRentDatabaseEntitiesActual")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autopark> Autopark { get; set; }
        public virtual DbSet<Fixes> Fixes { get; set; }
        public virtual DbSet<ModelTable> ModelTable { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Rents> Rents { get; set; }
        public virtual DbSet<TechMessages> TechMessages { get; set; }
        public virtual DbSet<TypeTable> TypeTable { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
