//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixes
    {
        public int fixID { get; set; }
        public int autoID { get; set; }
        public string Description { get; set; }
        public System.DateTime Appeared { get; set; }
        public System.DateTime Fixed { get; set; }
    
        public virtual Autopark Autopark { get; set; }
    }
}
