//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int rentID { get; set; }
        public int userID { get; set; }
        public int autoID { get; set; }
        public int optionsID { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string insuranse { get; set; }
    
        public virtual Autopark Autopark { get; set; }
        public virtual Options Options { get; set; }
        public virtual TechMessages TechMessages { get; set; }
        public virtual Users Users { get; set; }
    }
}
